name: miga
description: A starting point for Dart libraries or applications.
version: 1.1.0
repository: https://github.com/ross96D/miga

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  chalkdart: ^3.0.5
  textwrap: ^2.1.0
  characters: ^1.4.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
